config/routes.rb
Rubyintern2::Application.routes.draw do
  resources :internships

  root :to => 'internships#index'

end

app/models/internship.rb
class Internship < ActiveRecord::Base
  validates_presence_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/internships_controller.rb
class InternshipsController < ApplicationController
  # GET /internships
  # GET /internships.json
  def index
    @search = Internship.search(params[:search]) 
    @internships = @search.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @internships }
    end
  end

  # GET /internships/1
  # GET /internships/1.json
  def show
    @internship = Internship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @internship }
    end
  end

  # GET /internships/new
  # GET /internships/new.json
  def new
    @internship = Internship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @internship }
    end
  end

  # GET /internships/1/edit
  def edit
    @internship = Internship.find(params[:id])
  end

  # POST /internships
  # POST /internships.json
  def create
    @internship = Internship.new(params[:internship])

    respond_to do |format|
      if @internship.save
        format.html { redirect_to @internship, notice: 'Internship was successfully created.' }
        format.json { render json: @internship, status: :created, location: @internship }
      else
        format.html { render action: "new" }
        format.json { render json: @internship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /internships/1
  # PUT /internships/1.json
  def update
    @internship = Internship.find(params[:id])

    respond_to do |format|
      if @internship.update_attributes(params[:internship])
        format.html { redirect_to @internship, notice: 'Internship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @internship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /internships/1
  # DELETE /internships/1.json
  def destroy
    @internship = Internship.find(params[:id])
    @internship.destroy

    respond_to do |format|
      format.html { redirect_to internships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/internships_helper.rb
module InternshipsHelper
end

app/views/internships/_form.html.haml
= simple_form_for(@internship, :html => { :class => 'form-horizontal' } ) do |f|
  - if @internship.errors.any?
    #error_explanation
      %h2
        = pluralize(@internship.errors.count, "error")
      prohibited this internship from being saved:
    %ul
      - @internship.errors.full_messages.each do |msg|
        %li= msg 
  .field
    = f.input :title
  .field
    = f.input :sector
  .field
    = f.input :languages
  .field
    = f.input :length
  .field
    = f.input :location
  .field
    = f.input :job_type
  .field
    = f.input :hours
  .field
    = f.input :salary
  .field
    = f.input :company_description
  .field
    = f.input :internship
  .actions
    = f.submit

app/views/internships/edit.html.haml
%h1 Editing internship

= render 'form' 

= link_to 'Show', @internship |
= link_to 'Back', internships_path 

app/views/internships/index.html.haml
.row.new-internship
  %p.new-link
    = link_to new_internship_path, class: 'btn btn-success', title: t(:new) do
      %i.icon-plus-sign.icon-white
      %span.new-link.link-name= t(:new)


%h1.division Latests internship Opportunities 

.row
  .span12
    = form_for @search, html: {class: 'form-search'}  do |f| 
      = f.label :title_contains, t(:search_title)
      = f.text_field :title_contains, class: '.input-medium search-query'
      %button{name: "commit", type: "submit", class: "btn btn-primary"}
        %i.icon-search.icon-white
        Search

%table.table
  %tr
    %th Location
    %th Title
    %th Company description
    %th Actions

  - @internships.each do |internship| 
    %tr
      %td
        = internship.location 
      %td
        = internship.title 
      %td
        = internship.company_description 
      %td
        = link_to internship_path(internship), class: 'btn btn-primary', title: t(:show) do
          %i.icon-share-alt.icon-white
          %span.show-link.link-name= t(:show)
        = link_to edit_internship_path(internship), class: 'btn btn-primary', title: t(:edit) do
          %i.icon-edit.icon-white
          %span.edit-link.link-name= t(:edit)
        = link_to internship, confirm: t(:delete_question), method: :delete, class: 'btn btn-danger', title: t(:delete) do
          %i.icon-trash.icon-white
          %span.delete-link.link-name= t(:delete)

app/views/internships/new.html.haml
%h1 New internship

= render 'form' 

= link_to 'Back', internships_path

app/views/internships/show.html.haml
%p#notice= notice
%p
  %b Title:
  = @internship.title
%p
  %b Sector:
  = @internship.sector
%p
  %b Languages:
  = @internship.languages
%p
  %b Length:
  = @internship.length
%p
  %b Location:
  = @internship.location
%p
  %b Type:
  = @internship.job_type
%p
  %b Hours:
  = @internship.hours
%p
  %b Salary:
  = @internship.salary
%p
  %b Company description:
  = @internship.company_description
%p
  %b Internship:
  = @internship.internship
= link_to 'Edit', edit_internship_path(@internship)
|
\#{link_to 'Back', internships_path}

app/views/layouts/application.html.haml
%html
  %head
    %title Rubyintern2
    = stylesheet_link_tag    "application", :media => "all"
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Open+Sans|Play|Metrophobic"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "#"} London Technical Internships
          .nav-collapse
            %ul.nav
              %li= link_to "About us"
              %li= link_to "Ideas and Suggestions"
              %li= link_to "Code on Github"
              %li= link_to "Issue Tracker"
    .container-fluid
      - flash.each do |name, msg|
        %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
          %a.close{"data-dismiss" => "alert"} ×
          = msg
      = yield
      %div